with open('trip_optimizer/web/model.mjs', 'a') as f:
    f.write("\n")
    f.write("export function encodeState(state) {\n")
    f.write("    return btoa(encodeURIComponent(JSON.stringify(state)));\n")
    f.write("}\n")
    f.write("export function decodeState(hash) {\n")
    f.write("    if (!hash || hash.length < 2) return null;\n")
    f.write("    try {\n")
    f.write("        return JSON.parse(decodeURIComponent(atob(hash.startsWith('#') ? hash.substring(1) : hash)));\n")
    f.write("    } catch(e) {\n")
    f.write("        return null;\n")
    f.write("    }\n")
    f.write("}\n")
